### ISSUE TITLE
Problem with bare repo

### ISSUE THREAD

**Issue by shulard** [josegonzalez/php-git#7]
Hello!

I want to use your interface on Bare repo as a viewer on my centralized server.
I have configured the project but it seems to have a problem with bare repo parsing.

Is it normal?
Have you experienced this kind of problem?

Thanks for your answer!

**Comment by maxdoom-com** [comment]
There are (at least) two things to do before it will work with bare repos.
(1) As far as i've seen, the listing will only work, if there are already commits to the repo. Try cloning and making a first commit to it.
(2) Be sure to set the $CONFIG['repo_suffix'] = ""; in config/core.php. Bare repos don't have a /.git/ - subdirectory (AFAIK).

**Comment by josegonzalez** [comment]
I'm no longer maintaining this repository. Pull requests welcome, but I won't be fixing any issues.
