### ISSUE TITLE
Imcompatible with PHP 5.4

### ISSUE THREAD

**Issue by josenobile** [josegonzalez/php-git#8]
Please, update the code to working with PHP 5.4.5

PHP Fatal error:  Call-time pass-by-reference has been removed in /var/www/html/git-php/libs/git.php on line 46

// Right way!
function myFunc(&$arg) { }
myFunc($var);
Rather than:

// Wrong way!
function myFunc($arg) { }
myFunc(&$arg);

**Comment by josegonzalez** [comment]
I'm no longer maintaining this repository. Pull requests welcome, but I won't be fixing any issues.
